import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { TopBar } from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--rubik-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} bg-ring relative bg-light-gray text-navy-dark dark:bg-navy-dark dark:text-white `}
      >
        <div className="absolute left-0 top-0 -z-50 text-[#EDF1F9] dark:text-[#2D3949] ">
          <DesktopImage />
          <MobileImage />
        </div>
        <TopBar />
        <main className="mx-auto flex w-fit flex-shrink-0 flex-col gap-10 self-stretch px-6 pt-8">
          {children}
        </main>
      </body>
    </html>
  );
}

const MobileImage = () => (
  <svg
    className="sm:hidden"
    width="375"
    height="812"
    viewBox="0 0 375 812"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      cx="-113.5"
      cy="323.5"
      r="416.5"
      stroke="currentColor"
      strokeWidth="144"
    />
  </svg>
);

const DesktopImage = () => (
  <svg
    className="max-sm:hidden"
    width="438"
    height="531"
    viewBox="0 0 438 531"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      cx="-50.5"
      cy="42.5"
      r="416.5"
      stroke="currentColor"
      strokeWidth="144"
    />
  </svg>
);
